"""Platform enums for the campaigns domain."""

from enum import Enum


class PlatformType(str, Enum):
    GOOGLE = "GOOGLE"
    META = "META"
    BING = "BING"


class CampaignType(str, Enum):
    SEARCH = "SEARCH"
    DISPLAY = "DISPLAY"
    SHOPPING = "SHOPPING"
    PERFORMANCE_MAX = "PERFORMANCE_MAX"
    APP = "APP"
    DEMAND_GEN = "DEMAND_GEN"
    AWARENESS = "AWARENESS"
    TRAFFIC = "TRAFFIC"
    ENGAGEMENT = "ENGAGEMENT"
    LEADS = "LEADS"
    SALES = "SALES"


class TemplateType(str, Enum):
    GOOGLE_RESPONSIVE_SEARCH_AD = "GOOGLE_RESPONSIVE_SEARCH_AD"
    GOOGLE_RESPONSIVE_DISPLAY_AD = "GOOGLE_RESPONSIVE_DISPLAY_AD"
    GOOGLE_PERFORMANCE_MAX = "GOOGLE_PERFORMANCE_MAX"
    GOOGLE_SHOPPING_PRODUCT_AD = "GOOGLE_SHOPPING_PRODUCT_AD"
    GOOGLE_APP_INSTALLS = "GOOGLE_APP_INSTALLS"
    GOOGLE_DEMAND_GEN_VIDEO = "GOOGLE_DEMAND_GEN_VIDEO"
    GOOGLE_DEMAND_GEN_IMAGE = "GOOGLE_DEMAND_GEN_IMAGE"
    BING_RESPONSIVE_SEARCH_AD = "BING_RESPONSIVE_SEARCH_AD"
    BING_RESPONSIVE_DISPLAY_AD = "BING_RESPONSIVE_DISPLAY_AD"
    BING_PERFORMANCE_MAX = "BING_PERFORMANCE_MAX"
    BING_SHOPPING_PRODUCT_AD = "BING_SHOPPING_PRODUCT_AD"
    BING_APP_INSTALL_AD = "BING_APP_INSTALL_AD"
    BING_VIDEO_AD = "BING_VIDEO_AD"
    META_SINGLE_IMAGE_AD = "META_SINGLE_IMAGE_AD"
    META_CAROUSEL_AD = "META_CAROUSEL_AD"
    META_VIDEO_AD = "META_VIDEO_AD"
    META_COLLECTION_AD = "META_COLLECTION_AD"


class GoogleCallToAction(str, Enum):
    APPLY_NOW = "Apply now"
    BOOK_NOW = "Book now"
    CONTACT_US = "Contact us"
    DOWNLOAD = "Download"
    GET_QUOTE = "Get quote"
    INSTALL = "Install"
    LEARN_MORE = "Learn more"
    SEE_MORE = "See more"
    SHOP_NOW = "Shop now"
    SIGN_UP = "Sign up"
    SUBSCRIBE = "Subscribe"
    VISIT_SITE = "Visit site"


class BingCallToAction(str, Enum):
    ACT_NOW = "ActNow"
    APPLY_NOW = "ApplyNow"
    BET_NOW = "BetNow"
    BID_NOW = "BidNow"
    BOOK_A_CAR = "BookACar"
    BOOK_HOTEL = "BookHotel"
    BOOK_NOW = "BookNow"
    BROWSE = "Browse"
    BUY_NOW = "BuyNow"
    CHAT_NOW = "ChatNow"
    COMPARE = "Compare"
    CONTACT_US = "ContactUs"
    COUPON = "Coupon"
    DONATE = "Donate"
    DOWNLOAD = "Download"
    EMAIL_NOW = "EmailNow"
    ENROLL_NOW = "EnrollNow"
    EXPLORE = "Explore"
    FILE_NOW = "FileNow"
    FIND_JOB = "FindJob"
    FREE_PLAY = "FreePlay"
    FREE_QUOTE = "FreeQuote"
    FREE_TRIAL = "FreeTrial"
    GET_DEALS = "GetDeals"
    GET_OFFER = "GetOffer"
    GET_QUOTE = "GetQuote"
    JOIN_NOW = "JoinNow"
    LEARN_MORE = "LearnMore"
    LISTEN_NOW = "ListenNow"
    LOG_IN = "LogIn"
    MESSAGE = "Message"
    NEW_CARS = "NewCars"
    ORDER_NOW = "OrderNow"
    PLAY_GAME = "PlayGame"
    PLAY_NOW = "PlayNow"
    POST_JOB = "PostJob"
    REGISTER = "Register"
    RENT_A_CAR = "RentACar"
    RENT_NOW = "RentNow"
    RESERVE = "Reserve"
    SALE = "Sale"
    SAVE_NOW = "SaveNow"
    SCHEDULE = "Schedule"
    SEE_MENU = "SeeMenu"
    SEE_MORE = "SeeMore"
    SEE_OFFER = "SeeOffer"
    SELL_NOW = "SellNow"
    SHOP_NOW = "ShopNow"
    SHOWTIMES = "Showtimes"
    SIGN_IN = "SignIn"
    SIGN_UP = "SignUp"
    START_FREE = "StartFree"
    START_NOW = "StartNow"
    SUBSCRIBE = "Subscribe"
    TEST_DRIVE = "TestDrive"
    TRY_NOW = "TryNow"
    USED_CARS = "UsedCars"
    VIEW_CARS = "ViewCars"
    VIEW_NOW = "ViewNow"
    VIEW_PLANS = "ViewPlans"
    VISIT_SITE = "VisitSite"
    VOTE_NOW = "VoteNow"
    WATCH = "Watch"
    WATCH_MORE = "WatchMore"
    WATCH_NOW = "WatchNow"
    DIRECTIONS = "Directions"
    FIND_STORE = "FindStore"
    SWITCH_NOW = "SwitchNow"
    VISIT_STORE = "VisitStore"
    RENEW_NOW = "RenewNow"
    REORDER = "Reorder"
    DEFAULT = "Default"
    NO_BUTTON = "NoButton"
    INSTALL = "Install"
    ADD_TO_CART = "AddToCart"
    BOOK_TRAVEL = "BookTravel"
    BUY = "Buy"
    OPEN_LINK = "OpenLink"
    REGISTER_NOW = "RegisterNow"
    BUILD_NOW = "BuildNow"
    DEALERS = "Dealers"
    GET_DEMO = "GetDemo"
    GET_NOW = "GetNow"
    GO_TO_DEMO = "GoToDemo"
    SEE_DEMO = "SeeDemo"
    SEE_MODELS = "SeeModels"
    SEE_OFFERS = "SeeOffers"
    VIEW_DEMO = "ViewDemo"
    CUSTOM_TEXT = "CustomText"
    DISCOVER = "Discover"
    DISMISS = "Dismiss"
    APPLY = "Apply"
    VIEW_QUOTE = "ViewQuote"
    JOIN = "Join"
    ATTEND = "Attend"
    REQUEST_DEMO = "RequestDemo"


class Gender(str, Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"
    ALL = "ALL"


class BudgetType(str, Enum):
    DAILY = "DAILY"
    LIFETIME = "LIFETIME"


class AssetGroupStatus(str, Enum):
    PAUSED = "PAUSED"
    LIVE = "LIVE"
    ARCHIVED = "ARCHIVED"


class SlotDataOperation(str, Enum):
    ADD = "ADD"
    UPDATE = "UPDATE"
    REMOVE = "REMOVE"


class CampaignTargetingType(str, Enum):
    GEO = "GEO"
    AGE = "AGE"
    GENDER = "GENDER"
    INTEREST = "INTEREST"
    AUDIENCE = "AUDIENCE"
    KEYWORD = "KEYWORD"
    LANGUAGE = "LANGUAGE"


class AdGroupTargetingType(str, Enum):
    GEO = "GEO"
    AGE = "AGE"
    GENDER = "GENDER"
    INTEREST = "INTEREST"
    AUDIENCE = "AUDIENCE"
    KEYWORD = "KEYWORD"
    LANGUAGE = "LANGUAGE"
