/**
 * Meta Ads API — campaign creation
 *
 * Creates a full campaign structure: Campaign → AdSet(s) → Ad(s)
 * using the Media Plan generated by the strategy agent.
 */

import type { MediaPlan, AdTypePlan, AdCreative } from '../campaign/transformers';

const META_API_BASE = 'https://graph.facebook.com/v23.0';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type MetaCampaignResult = {
  campaignId: string;
  adSetIds: string[];
  adIds: string[];
};

type MetaApiError = {
  error?: { message?: string; code?: number };
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function metaPost<T>(
  endpoint: string,
  params: Record<string, unknown>,
  token: string
): Promise<T> {
  const body = new URLSearchParams({ access_token: token });
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null) {
      body.set(key, typeof value === 'object' ? JSON.stringify(value) : String(value));
    }
  }

  const res = await fetch(`${META_API_BASE}/${endpoint}`, {
    method: 'POST',
    body,
    signal: AbortSignal.timeout(30000)
  });

  const json = (await res.json()) as T & MetaApiError;
  if (!res.ok || (json as MetaApiError).error) {
    const errMsg = (json as MetaApiError).error?.message ?? `Meta API error: ${res.status}`;
    throw new Error(errMsg);
  }
  return json;
}

// ---------------------------------------------------------------------------
// Objective mapping
// ---------------------------------------------------------------------------

const OBJECTIVE_MAP: Record<string, string> = {
  SALES: 'OUTCOME_SALES',
  LEADS: 'OUTCOME_LEADS',
  WEBSITE_TRAFFIC: 'OUTCOME_TRAFFIC',
  BRAND_AWARENESS: 'OUTCOME_AWARENESS',
  AWARENESS: 'OUTCOME_AWARENESS',
  TRAFFIC: 'OUTCOME_TRAFFIC',
  ENGAGEMENT: 'OUTCOME_ENGAGEMENT',
  APP_PROMOTION: 'OUTCOME_APP_PROMOTION'
};

function mapObjective(objective: string): string {
  return OBJECTIVE_MAP[objective.toUpperCase()] ?? 'OUTCOME_SALES';
}

// ---------------------------------------------------------------------------
// Optimization goal mapping per ad type
// ---------------------------------------------------------------------------

function getOptimizationGoal(adType: string, objective: string): string {
  const at = adType.toLowerCase();
  const obj = objective.toUpperCase();

  if (at.includes('lead')) return 'LEAD_GENERATION';
  if (obj === 'LEADS' || obj === 'OUTCOME_LEADS') return 'LEAD_GENERATION';
  if (obj === 'OUTCOME_AWARENESS' || obj === 'AWARENESS') return 'REACH';
  if (obj === 'OUTCOME_TRAFFIC' || obj === 'TRAFFIC') return 'LINK_CLICKS';
  return 'CONVERSIONS';
}

function getBillingEvent(optimizationGoal: string): string {
  if (optimizationGoal === 'REACH') return 'IMPRESSIONS';
  if (optimizationGoal === 'LINK_CLICKS') return 'LINK_CLICKS';
  return 'IMPRESSIONS';
}

// ---------------------------------------------------------------------------
// Placement mapping per ad type
// ---------------------------------------------------------------------------

function getPlacement(adType: string): { publisher_platforms: string[]; facebook_positions: string[]; instagram_positions: string[] } {
  const at = adType.toLowerCase();
  if (at.includes('reels')) {
    return {
      publisher_platforms: ['facebook', 'instagram'],
      facebook_positions: ['reels'],
      instagram_positions: ['reels']
    };
  }
  if (at.includes('stories')) {
    return {
      publisher_platforms: ['facebook', 'instagram'],
      facebook_positions: ['story'],
      instagram_positions: ['story']
    };
  }
  // Feed / generic
  return {
    publisher_platforms: ['facebook', 'instagram', 'audience_network'],
    facebook_positions: ['feed'],
    instagram_positions: ['stream']
  };
}

// ---------------------------------------------------------------------------
// Location targeting
// ---------------------------------------------------------------------------

function buildGeoSpec(targeting: AdTypePlan['targeting']): Record<string, unknown> {
  const locs = targeting.locations as unknown[];
  const countries: string[] = [];

  for (const loc of locs) {
    if (typeof loc === 'string') {
      countries.push(loc.toUpperCase().slice(0, 2));
    } else if (loc && typeof loc === 'object') {
      const l = loc as { country?: string; raw?: string };
      const country = l.country || l.raw?.slice(0, 2) || '';
      if (country) countries.push(country.toUpperCase());
    }
  }

  if (countries.length === 0) countries.push('US');

  return {
    countries: [...new Set(countries)]
  };
}

// ---------------------------------------------------------------------------
// Age mapping
// ---------------------------------------------------------------------------

function parseAgeRange(ageRange: string): { age_min: number; age_max: number } {
  const match = /(\d+)[^\d]+(\d+)?/.exec(ageRange);
  if (match) {
    const min = parseInt(match[1] ?? '18', 10);
    const max = match[2] ? parseInt(match[2], 10) : 65;
    return { age_min: Math.max(13, min), age_max: Math.min(65, max) };
  }
  return { age_min: 18, age_max: 65 };
}

// ---------------------------------------------------------------------------
// Main campaign creation function
// ---------------------------------------------------------------------------

export async function createMetaCampaign(
  adAccountId: string,
  accessToken: string,
  mediaPlan: MediaPlan,
  facebookPageId?: string
): Promise<MetaCampaignResult> {
  const metaPlatform = mediaPlan.platforms.find((p) => p.platform === 'meta');
  if (!metaPlatform) throw new Error('No Meta platform in media plan');

  const objective = mapObjective(mediaPlan.objective);

  // 1. Create the campaign
  const campaignRes = await metaPost<{ id: string }>(
    `act_${adAccountId}/campaigns`,
    {
      name: mediaPlan.campaignName,
      objective,
      status: 'PAUSED', // Start paused so user can review
      special_ad_categories: JSON.stringify([]),
      ...(mediaPlan.totalBudget > 0
        ? { daily_budget: Math.round((mediaPlan.dailyBudget || mediaPlan.totalBudget / (mediaPlan.duration || 30)) * 100) }
        : {})
    },
    accessToken
  );

  const metaCampaignId = campaignRes.id;
  const adSetIds: string[] = [];
  const adIds: string[] = [];

  // 2. Create ad sets and ads for each ad type
  for (const adType of metaPlatform.adTypes) {
    const optimizationGoal = getOptimizationGoal(adType.adType, mediaPlan.objective);
    const billingEvent = getBillingEvent(optimizationGoal);
    const placement = getPlacement(adType.adType);
    const geoSpec = buildGeoSpec(adType.targeting);
    const { age_min, age_max } = parseAgeRange(adType.targeting.ageRange);

    const genderMap: Record<string, number[]> = {
      Male: [1],
      Female: [2],
      All: [],
      GENDER_MALE: [1],
      GENDER_FEMALE: [2],
      GENDER_UNDETERMINED: []
    };
    const genders = genderMap[adType.targeting.gender] ?? [];

    const adSetBudget = adType.budget
      ? Math.round(adType.budget * 100 / (mediaPlan.duration || 30))
      : Math.round((metaPlatform.budget / Math.max(metaPlatform.adTypes.length, 1) * 100) / (mediaPlan.duration || 30));

    const targeting: Record<string, unknown> = {
      geo_locations: geoSpec,
      age_min,
      age_max,
      ...(genders.length > 0 ? { genders } : {}),
      publisher_platforms: placement.publisher_platforms,
      facebook_positions: placement.facebook_positions,
      instagram_positions: placement.instagram_positions
    };

    const adSetRes = await metaPost<{ id: string }>(
      `act_${adAccountId}/adsets`,
      {
        name: `${adType.adType} - ${mediaPlan.campaignName}`,
        campaign_id: metaCampaignId,
        optimization_goal: optimizationGoal,
        billing_event: billingEvent,
        daily_budget: Math.max(adSetBudget, 100), // min $1/day
        targeting: JSON.stringify(targeting),
        status: 'PAUSED',
        start_time: mediaPlan.startDate
          ? Math.floor(new Date(mediaPlan.startDate).getTime() / 1000)
          : Math.floor(Date.now() / 1000 + 3600),
        ...(mediaPlan.endDate
          ? { end_time: Math.floor(new Date(mediaPlan.endDate).getTime() / 1000) }
          : {})
      },
      accessToken
    );

    adSetIds.push(adSetRes.id);

    // 3. Create ads for each creative
    for (const ad of adType.ads.slice(0, 3)) {
      try {
        const adId = await createMetaAd(
          adAccountId,
          accessToken,
          adSetRes.id,
          ad,
          adType.adType,
          mediaPlan.campaignName,
          facebookPageId
        );
        if (adId) adIds.push(adId);
      } catch {
        // Non-fatal — ad creation failure shouldn't kill the whole publish
      }
    }
  }

  return { campaignId: metaCampaignId, adSetIds, adIds };
}

async function createMetaAd(
  adAccountId: string,
  accessToken: string,
  adSetId: string,
  ad: AdCreative,
  adType: string,
  campaignName: string,
  facebookPageId?: string
): Promise<string | null> {
  if (!facebookPageId) return null; // Can't create ads without a page

  const headline = ad.headlines[0] ?? campaignName;
  const body = ad.descriptions[0] ?? headline;
  const callToAction = ad.ctaText?.toUpperCase().replace(/\s+/g, '_') ?? 'LEARN_MORE';
  const validCtas = ['APPLY_NOW', 'BOOK_TRAVEL', 'BUY_NOW', 'CONTACT_US', 'DONATE_NOW', 'DOWNLOAD', 'GET_DIRECTIONS', 'GET_OFFER', 'GET_QUOTE', 'INSTALL_APP', 'LEARN_MORE', 'LISTEN_MUSIC', 'MESSAGE_PAGE', 'OPEN_LINK', 'ORDER_NOW', 'SHOP_NOW', 'SIGN_UP', 'SUBSCRIBE', 'WATCH_MORE'];
  const safeCta = validCtas.includes(callToAction) ? callToAction : 'LEARN_MORE';

  const objectStory: Record<string, unknown> = {
    page_id: facebookPageId,
    link_data: {
      link: ad.destinationUrl || 'https://example.com',
      message: body,
      name: headline,
      call_to_action: {
        type: safeCta,
        value: { link: ad.destinationUrl || 'https://example.com' }
      }
    }
  };

  // Add image if available (skip base64 data URLs — too large for URL params)
  const imageUrl = ad.imageUrls[0];
  if (imageUrl && imageUrl.startsWith('https://')) {
    (objectStory.link_data as Record<string, unknown>).picture = imageUrl;
  }

  const creativeRes = await metaPost<{ id: string }>(
    `act_${adAccountId}/adcreatives`,
    {
      name: `Creative - ${headline.slice(0, 40)}`,
      object_story_spec: JSON.stringify(objectStory)
    },
    accessToken
  );

  const adRes = await metaPost<{ id: string }>(
    `act_${adAccountId}/ads`,
    {
      name: `Ad - ${adType} - ${headline.slice(0, 30)}`,
      adset_id: adSetId,
      creative: JSON.stringify({ creative_id: creativeRes.id }),
      status: 'PAUSED'
    },
    accessToken
  );

  return adRes.id;
}
