{{- if and (hasKey .Values "secrets") (hasKey .Values.secrets "token") (hasKey .Values.secrets "uid") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  token: {{ .Values.secrets.token | b64enc }}
  uid: {{ .Values.secrets.uid | b64enc }}
  {{- end }}
