apiVersion: v1
kind: Service
metadata:
  name: {{ include "accelerate-agentic-service.fullname" . }}
  labels:
    {{- include "accelerate-agentic-service.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace}}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: main-api
  selector:
    {{- include "accelerate-agentic-service.selectorLabels" . | nindent 4 }}
