"""Analytics insights endpoints — AI-generated anomaly detection and actionable insights."""
from __future__ import annotations

import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from core.auth import verify_internal_key
from core.database import get_pool
from services.insight_engine import generate_insights

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/analytics/insights", tags=["insights"])


class DismissBody(BaseModel):
    pass  # insight_type comes from path parameter


@router.get("", dependencies=[Depends(verify_internal_key)])
async def get_insights(org_id: str):
    """Return prioritised actionable insights for the organisation.

    Insights are generated by analysing analytics_events and commerce data.
    Falls back to realistic mock insights if the DB tables are not yet populated.
    """
    pool = await get_pool()
    insights = await generate_insights(org_id, pool)
    return {
        "insights": insights,
        "total": len(insights),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


@router.post("/dismiss/{insight_type}", dependencies=[Depends(verify_internal_key)])
async def dismiss_insight(insight_type: str, org_id: str):
    """Mark an insight type as dismissed for the organisation.

    Stores the dismissal in the dismissed_insights table if it exists,
    otherwise returns success (ephemeral dismissal).
    """
    pool = await get_pool()
    try:
        now = datetime.now(timezone.utc)
        await pool.execute(
            """
            INSERT INTO dismissed_insights (org_id, insight_type, dismissed_at)
            VALUES ($1, $2, $3)
            ON CONFLICT (org_id, insight_type) DO UPDATE SET dismissed_at = EXCLUDED.dismissed_at
            """,
            org_id,
            insight_type,
            now,
        )
    except Exception as exc:
        logger.debug("dismissed_insights table not available: %s — returning ok anyway", exc)

    return {"ok": True, "insight_type": insight_type, "org_id": org_id}
